add_subdirectory(01-widgets-basics)
add_subdirectory(02-qml-quick-basics)
add_subdirectory(03-quick-controls-styling)
add_subdirectory(04-networking)
add_subdirectory(05-concurrency-async)
add_subdirectory(06-sql-persistence)
add_subdirectory(07-state-machine)
add_subdirectory(08-serial-and-devices)
add_subdirectory(09-latest-qt-release-features)
add_subdirectory(10-custom-rendering-and-xr)
