#!/usr/bin/env python3
"""Requirements traceability report for QtTutorial.

Walks the repo tree looking for:
  - framework-tour/<name>/            (every immediate subdirectory)
  - industries/<industry>/{onboard,offboard}-<name>/

For each one found, checks whether a matching test directory containing a
CMakeLists.txt exists:
  - tests/framework-tour/<name>/CMakeLists.txt
  - tests/industries/<industry>/<name>/CMakeLists.txt

Writes a markdown traceability table to docs/qa/traceability.md mapping each
module/example to whether it has a test directory, and which REQ-* IDs from
requirements/requirements.md it satisfies (or fails).

This is intentionally read-only against the source tree: it never creates,
deletes or moves framework-tour/industries/tests directories, and the only
file it writes is docs/qa/traceability.md.

Exit status:
  0  every framework-tour module and industry example has a matching test
     directory with a CMakeLists.txt.
  1  at least one module/example is missing its test directory (a "hard gap"
     — mirrors the reference project's traceability gate, scaled down: a
     missing test directory fails this check rather than merely being
     flagged for review).
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FRAMEWORK_TOUR_DIR = REPO_ROOT / "framework-tour"
INDUSTRIES_DIR = REPO_ROOT / "industries"
TESTS_DIR = REPO_ROOT / "tests"
OUTPUT_PATH = REPO_ROOT / "docs" / "qa" / "traceability.md"

# Non-module files/dirs that can legitimately sit alongside real modules at
# the framework-tour/ and industries/<industry>/ top levels.
FRAMEWORK_TOUR_IGNORE = {"CMakeLists.txt"}
INDUSTRY_IGNORE = {"CMakeLists.txt"}


@dataclass
class Entry:
    category: str          # "framework-tour" or "industries"
    display_name: str      # what shows in the table's first column
    test_dir: Path         # expected tests/... directory
    req_ids: list[str]     # REQ-* IDs this entry is checked against

    @property
    def has_test_dir(self) -> bool:
        return (self.test_dir / "CMakeLists.txt").is_file()


def find_framework_tour_entries() -> list[Entry]:
    entries: list[Entry] = []
    if not FRAMEWORK_TOUR_DIR.is_dir():
        return entries
    for child in sorted(FRAMEWORK_TOUR_DIR.iterdir()):
        if not child.is_dir():
            continue
        if child.name in FRAMEWORK_TOUR_IGNORE:
            continue
        name = child.name
        entries.append(
            Entry(
                category="framework-tour",
                display_name=f"framework-tour/{name}",
                test_dir=TESTS_DIR / "framework-tour" / name,
                req_ids=["REQ-FW-03", "REQ-FW-04"],
            )
        )
    return entries


def find_industry_entries() -> list[Entry]:
    entries: list[Entry] = []
    if not INDUSTRIES_DIR.is_dir():
        return entries
    for industry_dir in sorted(INDUSTRIES_DIR.iterdir()):
        if not industry_dir.is_dir():
            continue
        if industry_dir.name in INDUSTRY_IGNORE:
            continue
        industry = industry_dir.name
        for example_dir in sorted(industry_dir.iterdir()):
            if not example_dir.is_dir():
                continue
            name = example_dir.name
            if not (name.startswith("onboard-") or name.startswith("offboard-")):
                continue
            req_ids = ["REQ-IND-02", "REQ-IND-03"]
            if name.startswith("onboard-"):
                req_ids.append("REQ-IND-04")
            else:
                req_ids.append("REQ-IND-05")
            entries.append(
                Entry(
                    category="industries",
                    display_name=f"industries/{industry}/{name}",
                    test_dir=TESTS_DIR / "industries" / industry / name,
                    req_ids=req_ids,
                )
            )
    return entries


def render_report(entries: list[Entry]) -> str:
    lines = [
        "# Requirements Traceability Report",
        "",
        "Generated by `tools/trace_report.py`. Do not edit by hand — rerun the",
        "script to regenerate this file after adding or removing a",
        "framework-tour module or industry example.",
        "",
        "| Module / Example | Has test dir? | Satisfies |",
        "|---|---|---|",
    ]
    for entry in entries:
        status = "yes" if entry.has_test_dir else "**NO**"
        reqs = ", ".join(entry.req_ids) if entry.has_test_dir else ", ".join(
            f"{r} (FAILED)" for r in entry.req_ids
        )
        lines.append(f"| `{entry.display_name}` | {status} | {reqs} |")

    missing = [e for e in entries if not e.has_test_dir]
    lines.append("")
    if missing:
        lines.append(
            f"**{len(missing)} of {len(entries)} module(s)/example(s) are missing "
            "a test directory.** See `requirements/requirements.md` for "
            "REQ-FW-04 / REQ-IND-03."
        )
    else:
        lines.append(
            f"All {len(entries)} module(s)/example(s) have a matching test "
            "directory with a CMakeLists.txt."
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    entries = find_framework_tour_entries() + find_industry_entries()

    report = render_report(entries)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(report, encoding="utf-8")
    print(report)

    missing = [e for e in entries if not e.has_test_dir]
    if missing:
        print(
            f"trace_report: FAIL — {len(missing)} module(s)/example(s) lack a "
            "test directory:",
            file=sys.stderr,
        )
        for entry in missing:
            print(f"  - {entry.display_name} (expected {entry.test_dir})", file=sys.stderr)
        return 1

    print(f"trace_report: OK — {len(entries)} module(s)/example(s) all traced.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
